name: saltstack-users-formula
source: https://github.com/bechtoldt/saltstack-users-formula
summary: SaltStack Formula for user and group management
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
